// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7N3Cn_mU10kNN5o4AG55XtqetTH4zSm8',
    appId: '1:873263492033:web:34d9475c8fc84462ea9d40',
    messagingSenderId: '873263492033',
    projectId: 'experience-e4e10',
    authDomain: 'experience-e4e10.firebaseapp.com',
    storageBucket: 'experience-e4e10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANHDeDZ4Kjw_3anP37Ec6DSxZKyAiA8dY',
    appId: '1:873263492033:android:fa37ebb278b5a468ea9d40',
    messagingSenderId: '873263492033',
    projectId: 'experience-e4e10',
    storageBucket: 'experience-e4e10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKB_LG9LR7c-RW8-2qk4hgKPufZeAYKaI',
    appId: '1:873263492033:ios:6be7cf626dc29e39ea9d40',
    messagingSenderId: '873263492033',
    projectId: 'experience-e4e10',
    storageBucket: 'experience-e4e10.firebasestorage.app',
    iosBundleId: 'com.example.experienceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKB_LG9LR7c-RW8-2qk4hgKPufZeAYKaI',
    appId: '1:873263492033:ios:6be7cf626dc29e39ea9d40',
    messagingSenderId: '873263492033',
    projectId: 'experience-e4e10',
    storageBucket: 'experience-e4e10.firebasestorage.app',
    iosBundleId: 'com.example.experienceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7N3Cn_mU10kNN5o4AG55XtqetTH4zSm8',
    appId: '1:873263492033:web:622bdba5c00ef9bcea9d40',
    messagingSenderId: '873263492033',
    projectId: 'experience-e4e10',
    authDomain: 'experience-e4e10.firebaseapp.com',
    storageBucket: 'experience-e4e10.firebasestorage.app',
  );
}
